.define STACK_TOP 1fff

; assets
.define BG1_SCBR_SIZE_HALF  3000
.define BG1_SCBR_SIZE       6000
.define BG2_TILES_SIZE      02e0
.define BG_PALETTES_SIZE      40
.define BG1_MAP_SIZE        0800
.define BG2_MAP_SIZE        0700

; OAM
.define OAML_SIZE   0200
.define OAM_SIZE    0220

; COLORS
.define C_BLACK   0000
.define C_GRAY2   0001
.define C_GRAY1   0002
.define C_GRAY0   0003
.define C_BROWN1  0004
.define C_BROWN0  0005
.define C_GREEN1  0006
.define C_GREEN0  0007
.define C_CYAN    0008
.define C_BLUE    0009
.define C_VIOLET  000a
.define C_MAGENTA 000b
.define C_RED     000c
.define C_ORANGE  000d
.define C_YELLOW  000e
.define C_WHITE   000f
